line-length = 100
indent-width = 4
exclude = [
    "docs",
    "artifacts",
    "ops",
]

[lint]
select = ["E", "F", "W", "I"]
ignore = ["E203", "E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
