export const studioBaselineData =
  "{\"ts\":\"2026-02-15T10:00:01.000Z\",\"event\":\"start\",\"attrs\":{\"skill.name\":\"Planner\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":0,\"gen_ai.usage.output_tokens\":0,\"latency_ms\":90,\"skill.policy_required\":false,\"skill.files\":\"docs/overview.md\"}}\n" +
  "{\"ts\":\"2026-02-15T10:00:04.000Z\",\"event\":\"end\",\"attrs\":{\"skill.name\":\"Planner\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":120,\"gen_ai.usage.output_tokens\":80,\"latency_ms\":140,\"skill.policy_required\":false,\"skill.files\":\"docs/overview.md\"}}\n" +
  "{\"ts\":\"2026-02-15T10:00:08.000Z\",\"event\":\"end\",\"attrs\":{\"skill.name\":\"Writer\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":180,\"gen_ai.usage.output_tokens\":120,\"latency_ms\":190,\"skill.policy_required\":false,\"skill.files\":\"docs/help.md,docs/faq.md\"}}\n" +
  "{\"ts\":\"2026-02-15T10:00:12.000Z\",\"event\":\"end\",\"attrs\":{\"skill.name\":\"Critic\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":90,\"gen_ai.usage.output_tokens\":40,\"latency_ms\":130,\"skill.policy_required\":false,\"skill.files\":\"README.md\"}}";

export const studioCurrentData =
  "{\"ts\":\"2026-02-15T11:00:01.000Z\",\"event\":\"start\",\"attrs\":{\"skill.name\":\"Planner\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":0,\"gen_ai.usage.output_tokens\":0,\"latency_ms\":120,\"skill.policy_required\":true,\"skill.files\":\"docs/overview.md\"}}\n" +
  "{\"ts\":\"2026-02-15T11:00:06.000Z\",\"event\":\"end\",\"attrs\":{\"skill.name\":\"Planner\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":210,\"gen_ai.usage.output_tokens\":150,\"latency_ms\":300,\"skill.policy_required\":true,\"skill.files\":\"docs/overview.md\"}}\n" +
  "{\"ts\":\"2026-02-15T11:00:13.000Z\",\"event\":\"error\",\"attrs\":{\"skill.name\":\"Writer\",\"gen_ai.request.model\":\"claude-3-5-sonnet\",\"gen_ai.usage.input_tokens\":320,\"gen_ai.usage.output_tokens\":260,\"latency_ms\":430,\"skill.policy_required\":true,\"skill.files\":\"docs/help.md,docs/faq.md\",\"status\":\"error\"}}";
