version: "3.9"

services:
  collector:
    image: otel/opentelemetry-collector:0.94.0
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otelcol-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.52.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./sample_metrics.prom:/etc/prometheus/sample_metrics.prom:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=skillscope
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
