name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[otlp,dev]

      - name: Ruff lint
        run: ruff check .

      - name: Markdown formatting check
        run: mdformat --check README.md docs

      - name: Type check
        run: mypy

      - name: Run tests
        run: pytest -q

      - name: Run demo commands
        run: |
          python -m skillscope.cli emit --demo
          python -m skillscope.cli analyze --demo

  artefacts:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Generate demo artefacts
        run: |
          mkdir -p artefacts-ci
          python -m skillscope.cli emit --demo > artefacts-ci/skillscope_demo_events.jsonl
          python -m skillscope.cli analyze --demo --format json > artefacts-ci/skillscope_demo_summary.json

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: skillscope-demo-artefacts
          path: artefacts-ci/
