name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[otlp,dev]

      - name: Run tests
        run: pytest -q

      - name: Run demo commands
        run: |
          python -m skillscope.cli emit --demo
          python -m skillscope.cli analyze --demo
